export const driversOpenF1 = [
  {
    broadcast_name: "M VERSTAPPEN",
    country_code: "NED",
    driver_number: 1,
    first_name: "Max",
    full_name: "Max VERSTAPPEN",
    headshot_url:
      "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/M/MAXVER01_Max_Verstappen/maxver01.png.transform/1col/image.png",
    last_name: "Verstappen",
    meeting_key: 1253,
    name_acronym: "VER",
    session_key: 9683,
    team_colour: "3671C6",
    team_name: "Red Bull Racing",
  },
  {
    broadcast_name: "L NORRIS",
    country_code: "GBR",
    driver_number: 4,
    first_name: "Lando",
    full_name: "Lando NORRIS",
    headshot_url:
      "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LANNOR01_Lando_Norris/lannor01.png.transform/1col/image.png",
    last_name: "Norris",
    meeting_key: 1253,
    name_acronym: "NOR",
    session_key: 9683,
    team_colour: "FF8000",
    team_name: "McLaren",
  },
  {
    broadcast_name: "G BORTOLETO",
    country_code: null,
    driver_number: 5,
    first_name: "Gabriel",
    full_name: "Gabriel BORTOLETO",
    headshot_url:
      "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/G/GABBOR01_Gabriel_Bortoleto/gabbor01.png.transform/1col/image.png",
    last_name: "Bortoleto",
    meeting_key: 1253,
    name_acronym: "BOR",
    session_key: 9683,
    team_colour: "52E252",
    team_name: "Kick Sauber",
  },
  {
    broadcast_name: "I HADJAR",
    country_code: null,
    driver_number: 6,
    first_name: "Isack",
    full_name: "Isack HADJAR",
    headshot_url:
      "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/I/ISAHAD01_Isack_Hadjar/isahad01.png.transform/1col/image.png",
    last_name: "Hadjar",
    meeting_key: 1253,
    name_acronym: "HAD",
    session_key: 9683,
    team_colour: "6692FF",
    team_name: "Racing Bulls ( RB F1 Team )",
  },
  {
    broadcast_name: "J DOOHAN",
    country_code: null,
    driver_number: 7,
    first_name: "Jack",
    full_name: "Jack DOOHAN",
    headshot_url:
      "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/J/JACDOO01_Jack_Doohan/jacdoo01.png.transform/1col/image.png",
    last_name: "Doohan",
    meeting_key: 1253,
    name_acronym: "DOO",
    session_key: 9683,
    team_colour: "0093CC",
    team_name: "Alpine",
  },
  {
    broadcast_name: "P GASLY",
    country_code: "FRA",
    driver_number: 10,
    first_name: "Pierre",
    full_name: "Pierre GASLY",
    headshot_url:
      "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/P/PIEGAS01_Pierre_Gasly/piegas01.png.transform/1col/image.png",
    last_name: "Gasly",
    meeting_key: 1253,
    name_acronym: "GAS",
    session_key: 9683,
    team_colour: "0093CC",
    team_name: "Alpine",
  },
  {
    broadcast_name: "A ANTONELLI",
    country_code: null,
    driver_number: 12,
    first_name: "Andrea Kimi",
    full_name: "Andrea Kimi ANTONELLI",
    headshot_url:
      "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/A/ANDANT01_Andrea%20Kimi_Antonelli/andant01.png.transform/1col/image.png",
    last_name: "Antonelli",
    meeting_key: 1253,
    name_acronym: "ANT",
    session_key: 9683,
    team_colour: "27F4D2",
    team_name: "Mercedes",
  },
  {
    broadcast_name: "F ALONSO",
    country_code: "ESP",
    driver_number: 14,
    first_name: "Fernando",
    full_name: "Fernando ALONSO",
    headshot_url:
      "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/F/FERALO01_Fernando_Alonso/feralo01.png.transform/1col/image.png",
    last_name: "Alonso",
    meeting_key: 1253,
    name_acronym: "ALO",
    session_key: 9683,
    team_colour: "229971",
    team_name: "Aston Martin",
  },
  {
    broadcast_name: "C LECLERC",
    country_code: "MON",
    driver_number: 16,
    first_name: "Charles",
    full_name: "Charles LECLERC",
    headshot_url:
      "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/C/CHALEC01_Charles_Leclerc/chalec01.png.transform/1col/image.png",
    last_name: "Leclerc",
    meeting_key: 1253,
    name_acronym: "LEC",
    session_key: 9683,
    team_colour: "E80020",
    team_name: "Ferrari",
  },
  {
    broadcast_name: "L STROLL",
    country_code: "CAN",
    driver_number: 18,
    first_name: "Lance",
    full_name: "Lance STROLL",
    headshot_url:
      "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LANSTR01_Lance_Stroll/lanstr01.png.transform/1col/image.png",
    last_name: "Stroll",
    meeting_key: 1253,
    name_acronym: "STR",
    session_key: 9683,
    team_colour: "229971",
    team_name: "Aston Martin",
  },
  {
    broadcast_name: "Y TSUNODA",
    country_code: "JPN",
    driver_number: 22,
    first_name: "Yuki",
    full_name: "Yuki TSUNODA",
    headshot_url:
      "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/Y/YUKTSU01_Yuki_Tsunoda/yuktsu01.png.transform/1col/image.png",
    last_name: "Tsunoda",
    meeting_key: 1253,
    name_acronym: "TSU",
    session_key: 9683,
    team_colour: "6692FF",
    team_name: "Racing Bulls ( RB F1 Team )",
  },
  {
    broadcast_name: "A ALBON",
    country_code: "THA",
    driver_number: 23,
    first_name: "Alexander",
    full_name: "Alexander ALBON",
    headshot_url:
      "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/A/ALEALB01_Alexander_Albon/alealb01.png.transform/1col/image.png",
    last_name: "Albon",
    meeting_key: 1253,
    name_acronym: "ALB",
    session_key: 9683,
    team_colour: "64C4FF",
    team_name: "Williams",
  },
  {
    broadcast_name: "N HULKENBERG",
    country_code: "GER",
    driver_number: 27,
    first_name: "Nico",
    full_name: "Nico HULKENBERG",
    headshot_url:
      "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/N/NICHUL01_Nico_Hulkenberg/nichul01.png.transform/1col/image.png",
    last_name: "Hulkenberg",
    meeting_key: 1253,
    name_acronym: "HUL",
    session_key: 9683,
    team_colour: "52E252",
    team_name: "Kick Sauber",
  },
  {
    broadcast_name: "L LAWSON",
    country_code: null,
    driver_number: 30,
    first_name: "Liam",
    full_name: "Liam LAWSON",
    headshot_url:
      "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LIALAW01_Liam_Lawson/lialaw01.png.transform/1col/image.png",
    last_name: "Lawson",
    meeting_key: 1253,
    name_acronym: "LAW",
    session_key: 9683,
    team_colour: "3671C6",
    team_name: "Red Bull Racing",
  },
  {
    broadcast_name: "E OCON",
    country_code: "FRA",
    driver_number: 31,
    first_name: "Esteban",
    full_name: "Esteban OCON",
    headshot_url:
      "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/E/ESTOCO01_Esteban_Ocon/estoco01.png.transform/1col/image.png",
    last_name: "Ocon",
    meeting_key: 1253,
    name_acronym: "OCO",
    session_key: 9683,
    team_colour: "B6BABD",
    team_name: "Haas F1 Team",
  },
  {
    broadcast_name: "L HAMILTON",
    country_code: "GBR",
    driver_number: 44,
    first_name: "Lewis",
    full_name: "Lewis HAMILTON",
    headshot_url:
      "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LEWHAM01_Lewis_Hamilton/lewham01.png.transform/1col/image.png",
    last_name: "Hamilton",
    meeting_key: 1253,
    name_acronym: "HAM",
    session_key: 9683,
    team_colour: "E80020",
    team_name: "Ferrari",
  },
  {
    broadcast_name: "C SAINZ",
    country_code: "ESP",
    driver_number: 55,
    first_name: "Carlos",
    full_name: "Carlos SAINZ",
    headshot_url:
      "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/C/CARSAI01_Carlos_Sainz/carsai01.png.transform/1col/image.png",
    last_name: "Sainz",
    meeting_key: 1253,
    name_acronym: "SAI",
    session_key: 9683,
    team_colour: "64C4FF",
    team_name: "Williams",
  },
  {
    broadcast_name: "G RUSSELL",
    country_code: "GBR",
    driver_number: 63,
    first_name: "George",
    full_name: "George RUSSELL",
    headshot_url:
      "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/G/GEORUS01_George_Russell/georus01.png.transform/1col/image.png",
    last_name: "Russell",
    meeting_key: 1253,
    name_acronym: "RUS",
    session_key: 9683,
    team_colour: "27F4D2",
    team_name: "Mercedes",
  },
  {
    broadcast_name: "O PIASTRI",
    country_code: "AUS",
    driver_number: 81,
    first_name: "Oscar",
    full_name: "Oscar PIASTRI",
    headshot_url:
      "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/O/OSCPIA01_Oscar_Piastri/oscpia01.png.transform/1col/image.png",
    last_name: "Piastri",
    meeting_key: 1253,
    name_acronym: "PIA",
    session_key: 9683,
    team_colour: "FF8000",
    team_name: "McLaren",
  },
  {
    broadcast_name: "O BEARMAN",
    country_code: null,
    driver_number: 87,
    first_name: "Oliver",
    full_name: "Oliver BEARMAN",
    headshot_url:
      "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/O/OLIBEA01_Oliver_Bearman/olibea01.png.transform/1col/image.png",
    last_name: "Bearman",
    meeting_key: 1253,
    name_acronym: "BEA",
    session_key: 9683,
    team_colour: "B6BABD",
    team_name: "Haas F1 Team",
  },
];
